name: learnship
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.3.4
  cupertino_tabbar: ^1.1.1
  youtube_player_flutter: ^7.0.0+7
  flutter_svg: ^0.19.1
  focused_menu: ^1.0.5
  youtube_api: ^0.8.0
  convex_bottom_bar: ^3.0.0
  
  fluttertoast: ^8.0.6
  image_picker: ^0.6.3+4
  shared_preferences: ^0.5.7+1
  keyboard_actions: ^3.3.0+1
  font_awesome_flutter: ^8.8.1
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.3
  image_cropper: ^1.3.1
  url_launcher: ^6.0.3
  photo_view: ^0.9.2
  # http: ^0.13.0
  # http_parser: ^4.0.0

  #Utilities
  cached_network_image: ^2.4.1
  enum_to_string: ^1.0.14
  meta: ^1.2.4
  equatable: ^1.2.5
  uuid: ^2.2.2

  md2_tab_indicator: ^1.0.2
  youtube_explode_dart: ^1.7.5
  youtube_parser: ^1.1.0
  downloads_path_provider: ^0.1.0
  console: ^4.1.0
  flutter_bloc: ^6.1.1

  #Firebase
  cloud_firestore: ^0.14.4
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/
    - assets/course_image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
